# .pre-commit-config.yaml
default_language_version:
  python: python3.12

repos:
  # ── Ruff: lint → auto-fix → format ───────────────────────────────────────────
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.4
    hooks:
      - id: ruff
        args: [--fix]
        language_version: python3.12
      - id: ruff-format
        language_version: python3.12

  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy          # strict mode lives in [tool.mypy]; flag no longer needed
        args: [--strict, "govdocverify", "tests"]
        pass_filenames: false

  # ── Bandit: security scan, reads settings from pyproject.toml ───────────────
  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.5
    hooks:
      - id: bandit
        args:
          [
            "-c", "pyproject.toml",        # load the TOML config
            "--severity-level", "medium",
            "--confidence-level", "medium",
            "-r", "govdocverify/",  # scan only the package code
          ]
        additional_dependencies: ["bandit[toml]"]  # enables TOML parsing :contentReference[oaicite:0]{index=0}

  # ── Semgrep: lightweight SAST ──────────────────────────────────────────────
  - repo: https://github.com/returntocorp/semgrep
    rev: v1.81.0
    hooks:
      - id: semgrep
        args: ["--config", "p/ci"]

  # ── Markdown & spelling checks ─────────────────────────────────────────────
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.17
    hooks:
      - id: mdformat
        additional_dependencies: [mdformat-ruff, mdformat-gfm]

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
      - id: codespell

  - repo: https://github.com/trailofbits/pip-audit
    rev: v2.7.2
    hooks:
      - id: pip-audit
        # Audit dependencies using requirements.txt for now
        args: ["-r", "requirements.txt"]

  # ── Local test runner ───────────────────────────────────────────────────────
  - repo: local
    hooks:
      - id: lint-staged
        name: lint-staged
        entry: python scripts/lint_staged.py
        language: system
        pass_filenames: false
      - id: pytest
        name: pytest
        entry: pytest
        language: system
        pass_filenames: false
