repos:
  - repo: https://github.com/astral-sh/ruff
    rev: "v0.5.1"
    hooks:
      - id: ruff
      - id: ruff-format
  - repo: https://github.com/psf/black
    rev: "24.4.2"
    hooks:
      - id: black
        language_version: python3.12
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.10.0"
    hooks:
      - id: mypy
  - repo: https://github.com/PyCQA/bandit
    rev: "1.9.0"
    hooks:
      - id: bandit
        args: ["-r"]
  - repo: https://github.com/pycqa/ruff-pre-commit
    rev: "v1.2.0"
    hooks:
      - id: ruff-licence
