site_name: GovDocVerify
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Developer Guide: developer-guide.md
  - Scenarios: scenarios.md
  - API Reference: api-reference.md
  - Check Categories: checks.md
theme:
  name: material
