[project]
name = "documentcheckertoolsandbox"
version = "0.1.0"
description = "Tool for checking documents against Federal writing standards."
requires-python = ">=3.11"
dependencies = [
    "gradio>=5.31.0",
    "fastapi>=0.100.0",
    "python-docx>=0.8.11",
    "beautifulsoup4>=4.12.0",
    "pdfkit>=1.0.0",
    "nltk>=3.9.1",
    "pandas>=2.2.1",
    "numpy>=1.24.3",
    "pydantic>=2.11.4",
    "colorama>=0.4.6",
    "typing-extensions>=4.9.0",
    "filetype>=1.2.0",
    "python-multipart>=0.0.20",
]

[[project.authors]]
name = "Eric Putnam"
email = "contact@example.com"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["documentcheckertool*"]
exclude = ["backend*", "frontend*", "tests*"]

[tool.black]
line-length = 100
target-version = ['py311']

[tool.isort]
profile = "black"

[tool.ruff]
line-length = 100

[tool.ruff.lint]
select = ["E", "F", "W", "C90", "I"]

[tool.mypy]
python_version = "3.11"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_no_return = true
warn_unreachable = true
ignore_missing_imports = true

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"

[tool.bandit]
exclude_dirs = ["tests"]
skips = ["B101"]

[tool.vulture]
exclude = ["tests/*", "setup.py"]
min-confidence = 100