name: CI

on:
  push:
    branches: [main, BugFixing]
  pull_request:
    branches: [main, BugFixing]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]

      - name: Ruff lint
        run: ruff check govdocverify tests

      - name: Black formatting
        run: black --check govdocverify tests

      - name: Static type checking
        run: mypy --config-file pyproject.toml govdocverify tests

      - name: Bandit security scan
        run: bandit -c pyproject.toml -r govdocverify

      - name: Audit dependencies
        run: pip-audit -r requirements.txt

  tests:
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.11"]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]

      - name: Run tests with coverage
        run: pytest --cov=govdocverify --cov-branch --cov-report=xml --cov-fail-under=70
