name: CI

on:
  push:
    branches: [ main, BugFixing ]
  pull_request:
    branches: [ main, BugFixing ]

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Install project (editable)
        run: pip install -e .

      - name: Run pre-commit checks
        run: pre-commit run --all-files

      - name: Run tests with coverage
        run: |
          pytest --cov=documentcheckertool --cov-report=xml

      - name: Check coverage >= 90%
        run: |
          python - <<'PY'
          import xml.etree.ElementTree as ET, sys
          coverage = float(ET.parse('coverage.xml').getroot().attrib['line-rate']) * 100
          print(f'Coverage: {coverage:.2f}%')
          if coverage < 90.0:
              print(f"::error::Test coverage {coverage:.2f}% is below 90%")
              sys.exit(1)
          PY

      - name: Audit dependencies
        run: pip-audit -r requirements.txt
