name: Sync to Hugging Face hub
on:
  push:
    branches: [main]

  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Clean repository
        run: |
          # Remove __pycache__ directories and files
          find . -type d -name "__pycache__" -exec rm -r {} +
          find . -type f -name "*.pyc" -delete
          find . -type f -name "*.pyo" -delete
          find . -type f -name "*.pyd" -delete

          # Stage deletions
          git add -A
          # Commit if there are changes
          git diff --cached --quiet || git commit -m "Remove Python cache and binary files before filter-branch"

          # Clean git history of binary files
          git filter-branch --force --index-filter \
            "git rm --cached --ignore-unmatch -r __pycache__/ *.pyc *.pyo *.pyd" \
            --prune-empty --tag-name-filter cat -- --all

          # Clean up refs and garbage
          git for-each-ref --format='delete %(refname)' refs/original/ | git update-ref --stdin
          git reflog expire --expire=now --all
          git gc --prune=now --aggressive

      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          echo "Setting up remote..."
          git remote add space https://Hoctar77:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/Hoctar77/DocumentCheckerToolSandbox
          echo "Pushing to Hugging Face..."
          git push space HEAD:main --force